name: synurang
description: "Flutter FFI + gRPC bridge for bidirectional Go/Dart communication"
version: 0.1.0
homepage: https://github.com/tempage/synurang
repository: https://github.com/tempage/synurang

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  protobuf: ^5.1.0
  grpc: ^4.0.1
  fixnum: ^1.1.0

dev_dependencies:
  ffigen: ^19.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.24.0


flutter:
  plugin:
    platforms:
      linux:
        ffiPlugin: true
